name: tp0

# Shared/Commons
x-client-base: &client-base
  image: client:latest
  entrypoint: /client
  networks:
    - testing_net
  depends_on:
    - server

services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
      - ./server/bets.csv:/bets.csv

  client1:
    <<: *client-base
    container_name: client1
    environment:
      - CLI_ID=1
      - NOMBRE=DAN1
      - APELLIDO=HUR1
      - DOCUMENTO=40000001
      - NACIMIENTO=2000-01-01
      - NUMERO=20001
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/bets.csv
  
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

